### ISSUE TITLE
It is completely unnecessary to grab the MSA client ID from multimc, when you can register one yourself.

### ISSUE THREAD

**Issue by ImperatorStorm** [videogame-hacker/som.codes#2]
See https://github.com/MultiMC/Launcher/blob/develop/notsecrets/Secrets.cpp#L9-L29.

**Comment by ImperatorStorm** [comment]
as a side note, I wouldn't exactly trust the PolyMC people, as they regularly trolled multimc and got blocked because of it.

**Comment by ghost** [comment]
Keep licking the boot.

**Comment by char** [comment]
it may not be necessary but it *is* more fun & less effort though :)

in terms of trusting the PolyMC people, we will see how the fork pans out. I do not have much stake in either I just like playing block game sometimes

I like how they just have the MSAClientID set to `17b47edd-c884-4997-926d-9e7f9a6b4647` in their CMake config instead of trying to obscure it from their users, though. Gives off more of a trusting & cooperative vibe compared to MMC

**Comment by ImperatorStorm** [comment]
> I like how they just have the MSAClientID set to 17b47edd-c884-4997-926d-9e7f9a6b4647 in their CMake config instead of trying to obscure it from their users, though. Gives off more of a trusting & cooperative vibe compared to MMC

Peterix hides it because he's liable if anyone uses it.

This applies to everyone who registers their own MSA ClientID.

For some reason, i don't think the PolyMC people understand this.
